[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "encode_convert"
version = "0.1.0"

# 依存ライブラリ
dependencies = ["pandas", "chardet", "PyYAML"]

[tool.setuptools]
packages = ["encode_convert"]
